name: "Build Documentation"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '20 18 * * 1'
  workflow_dispatch:

jobs:
  changed-files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Get changed files
    permissions:
      pull-requests: read
      contents: read
    outputs:
      # reference: https://github.com/tj-actions/changed-files#outputs-
      workflow: ${{ steps.changed-files.outputs.workflow_any_modified == 'true' }}
      docs: ${{ steps.changed-files.outputs.docs_any_modified == 'true' }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Get changed files
        if: ${{ !( github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' ) || !env.ACT }}
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          files_yaml: |
            workflow: &workflow
              - .github/workflows/doc-build.yml
            docs: &docs
              - *workflow
              - doc/manual/**
  build-docs:
    name: "Build Documentation"
    runs-on: ubuntu-latest
    needs: [ changed-files ]
    if: ${{ needs.changed-files.outputs.docs == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event.act == 'true' }}

    permissions:
      contents: read
      pull-requests: read

    strategy:
      fail-fast: false
      matrix:
        container:
          - "ehb1/usbuildtest:ubuntu22.04-qt5.15.10-qwt6.1.6"
          - "ehb1/usbuildtest:ubuntu24.04-qt6.8.3-qwt6.3.0"
          - "ehb1/usbuildtest:ubuntu24.04-qt6.10.0-qwt6.3.0"

    # Specify the container in which actions will run
    container:
      image: ${{ matrix.container }}
      options: --cpus 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Build Documentation
        run: |
          cd doc/manual
          make -j1
  check-status:
    if: always()
    needs: [ build-docs ]
    name: Check Documentation build status
    runs-on: ubuntu-latest
    steps:
      - name: Check statuses
        run: |
          RESULTS='${{ toJson(needs) }}'
          # Check for failures
          if echo $RESULTS | grep -q '"result": "failure"'; then
            echo "At least one Documentation build job failed."
            exit 1
          fi
          # Check for cancelled jobs
          if echo $RESULTS | grep -q '"result": "cancelled"'; then
            echo "At least one Documentation build job was cancelled."
            exit 1
          fi
          echo "All Documentation build jobs completed successfully or were skipped."
          exit 0